-------------------------------------------------------------------------------
Test set: models.NonEndangeredAnimalTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE! - in models.NonEndangeredAnimalTest
get_obtainTheProbabilityOfSurvival_3(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

save_returnsTrueIfSavesInDbCorrectly(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

animal_instantiatesCorrectlyAsAnimal_true(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

getAnimalAge_returnsAnimalAgeCorrectly_young(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

getRangerId_returnsRangerIdCorrectly_12(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

save_assignsIdToAnimal(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

getAnimalName_returnsAnimalNameCorrectly_tiger(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

equals_returnsTrueIfNameAndAgeAndHealthAndRangerIdAreEqual_true(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

find_returnsAnimalWithSameId_secondAnimal(models.NonEndangeredAnimalTest)  Time elapsed: 0.005 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

getAnimalHealth_returnsAnimalHealthStatusCorrectly_okay(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

all_returnsAllInstancesOfAnimal_true(models.NonEndangeredAnimalTest)  Time elapsed: 0 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The connection attempt failed.
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
Caused by: java.net.UnknownHostException: 

ec2-184-72-235-159.compute-1.amazonaws.com

